name: Anugular build workflow application

on:
  push:
    branches: [ main ]
jobs:
  angular-app:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkouts repo
         uses: actions/checkout@v2.8.0
      -  name: Setup Node.js environment
         uses: actions/setup-node@v6.5.0
         with: 
           node-version: 22.x
      -  name: Install dependencies
         run: npm install
      -  name: Build the package
         run: npm run build
